### ISSUE TITLE
demo_code with xaringan package

### ISSUE THREAD

**Issue by mrchypark** [kbodwin/demoR#8]
I use presentation package called xaringan. 

but xaringan build without demo_code.

![image](https://user-images.githubusercontent.com/6179259/62027131-e0fa4200-b217-11e9-8956-d842f61495de.png)

**Comment by kbodwin** [comment]
`xaringan` is high priority for us, too!  (As well as `ioslides` and `slidy`, ideally.)

**Comment by kbodwin** [comment]
Okay, we are up and running with:

- xaringan
- ioslides
- slidy
- revealjs

Let me know if you run into any issues, or if there are other packages that demoR isn't playing nice with.
